[package]
name = "zorigami"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "Backup and restore application."
repository = "https://github.com/nlfiedler/zorigami"
readme = "README.md"
keywords = ["backup", "archival"]
license = "BSD-2-Clause"

[dependencies]
actix-files = "0.1.4"
actix-web = "1.0.5"
base64 = "0.10.1"
chrono = "0.4.7"
cron = "0.6.0"
dotenv = "0.14.1"
env_logger = "0.7.0"
failure = "0.1.5"
fastcdc = "1.0.1"
futures = "0.1.28"
futures-fs = "0.0.5"
juniper = "0.14.0"
lazy_static = "1.3.0"
libc = "0.2.60"
log = "0.4.7"
md-5 = "0.8.0"
memmap = "0.7.0"
openssl = { version = "0.10", features = ["vendored"] }
reducer = "1.3.0"
rocksdb = "0.12.2"
rusoto_core = "0.41.0"
rusoto_credential = "0.41.0"
rusoto_s3 = "0.41.0"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10.1"
serde_json = "1.0"
sha-1 = "0.8.1"
sha2 = "0.8.0"
sodiumoxide = "0.2.4"
ssh2 = "0.4"
tar = "0.4.26"
tempfile = "3.1.0"
uuid = { version = "0.7", features = ["v5"] }
ulid = "0.3.1"
whoami = "0.5.3"
xattr = "0.2.2"
