[package]
name = "zorigami"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "Backup and restore application."
repository = "https://github.com/nlfiedler/zorigami"
readme = "README.md"
keywords = ["backup", "archival"]
license = "BSD-2-Clause"

[dependencies]
fastcdc = "1.0.1"
gpgme = "0.8.0"
hex = "0.3.2"
juniper = "0.11.1"
juniper_warp = "0.2.0"
log = "0.4.6"
memmap = "0.7.0"
pretty_env_logger = "0.3.0"
sha-1 = "0.8.1"
sha2 = "0.8.0"
tar = "0.4.20"
uuid = { version = "0.7", features = ["v5"] }
ulid = "0.3.1"
warp = "0.1.13"

[dev-dependencies]
tempfile = "3.0.6"
