[package]
name = "zorigami"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "Backup and restore application."
repository = "https://github.com/nlfiedler/zorigami"
readme = "README.md"
keywords = ["backup", "archival"]
license = "BSD-2-Clause"

[dependencies]
crypto-hash = "0.3.3"
fastcdc = "1.0.1"
hex = "0.3.2"
juniper = "0.11.1"
juniper_warp = "0.2.0"
log = "0.4.6"
memmap = "0.7.0"
pretty_env_logger = "0.3.0"
uuid = { version = "0.7", features = ["v5"] }
ulid = "0.3.1"
warp = "0.1.13"
