[workspace]
members = [
    "database/database_core",
    "database/database_rocks",
    "server",
    "stores/store_core",
    "stores/store_local",
    "stores/store_minio",
    "stores/store_sftp",
]
