[package]
name = "zorigami"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "Backup and restore application."
repository = "https://github.com/nlfiedler/zorigami"
readme = "README.md"
keywords = ["backup", "archival"]
license = "BSD-2-Clause"

[dependencies]
actix = "0.9"
actix-cors = "0.2"
actix-files = "0.2"
actix-rt = "1.0.0"
actix-web = "2.0"
base64 = "0.12.0"
blob-uuid = "0.4.0"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15.0"
env_logger = "0.7.0"
failure = "0.1.6"
failure_derive = "0.1.6"
fastcdc = "1.0.1"
flate2 = "1.0"
futures = "0.1.28"
futures-fs = "0.0.5"
juniper = "0.14.0"
lazy_static = "1.3.0"
libc = "0.2.60"
log = "0.4.7"
md-5 = "0.8.0"
memmap = "0.7.0"
reducer = "2.0"
rocksdb = "0.14.0"
rusoto_core = "0.42.0"
rusoto_credential = "0.42.0"
rusoto_s3 = "0.42.0"
rusty_ulid = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
serde_json = "1.0"
sha-1 = "0.8.1"
sha2 = "0.8.0"
sodiumoxide = "0.2.4"
ssh2 = "0.8"
tar = "0.4.26"
tempfile = "3.1.0"
time = "0.1"
uuid = { version = "0.8", features = ["serde", "v4", "v5"] }
whoami = "0.8"

[target.'cfg(windows)'.dependencies]
openssl = { version = "0.10" }

[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
xattr = "0.2.2"
