[package]
name = "zorigami"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "Backup and restore application."
repository = "https://github.com/nlfiedler/zorigami"
readme = "README.md"
keywords = ["backup", "archival"]
license = "BSD-2-Clause"

[dependencies]
base64 = "0.10.1"
dotenv = "0.13.0"
failure = "0.1.5"
fastcdc = "1.0.1"
futures = "0.1.25"
futures-fs = "0.0.5"
gpgme = "0.8.0"
juniper = "0.11.1"
juniper_warp = "0.2.0"
libc = "0.2.50"
log = "0.4.6"
md-5 = "0.8.0"
memmap = "0.7.0"
openssl = { version = "0.10", features = ["vendored"] }
pretty_env_logger = "0.3.0"
rocksdb = "0.11.0"
rusoto_core = "0.36.0"
rusoto_credential = "0.15.0"
rusoto_s3 = "0.36.0"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.9.0"
serde_json = "1.0"
sha-1 = "0.8.1"
sha2 = "0.8.0"
ssh2 = "0.3"
tar = "0.4.20"
uuid = { version = "0.7", features = ["v5"] }
ulid = "0.3.1"
warp = "0.1.13"
xattr = "0.2.2"

[dev-dependencies]
lazy_static = "1.2.0"
tempfile = "3.0.6"
