version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      DB_PATH: "/database"
      RUST_LOG: "info"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./tmp/packs
        target: /packstore
      - type: bind
        source: ./tmp/database
        target: /database
      - type: bind
        source: "."
        target: /datasets
