version: '3.7'

services:
  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    command: foo:pass:::upload
  minio:
    #
    # You can run the image to get help output:
    # $ docker run -p 9000:9000 --name minio1 minio/minio server
    #
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: AKIAJUI64O4WFEXAMPLE
      MINIO_SECRET_KEY: EdH8beEG6Qc9Th/irhm6YD+y1RQYivFyoExample
    command: server /data
