name: zorigami
description: Graphical user interface for the zorigami backup/restore application.
version: 1.0.0+1
homepage: https://github.com/nlfiedler/zorigami
repository: https://github.com/nlfiedler/zorigami.git
issue_tracker: https://github.com/nlfiedler/zorigami/issues
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  equatable: ^2.0.3
  form_builder_validators: ^9.0.0
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.1.0
  flutter_riverpod: ^2.4.9
  graphql: ^5.1.3
  intl: ^0.19.0
  oxidized: ^6.1.0
  progressive_time_picker: ^1.0.1

# work-around for https://github.com/flutter-form-builder-ecosystem/form_builder_validators/issues/90
dependency_overrides:
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.5
  environment_config: ^3.1.0
  flutter_lints: ^3.0.1
  http: ^1.2.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

environment_config:
  const: true
  fields:
    base_url:
      default: http://127.0.0.1:8080
      env_var: BASE_URL
