name: zorigami
description: Graphical user interface for the zorigami backup/restore application.
version: 1.0.0+1
homepage: https://github.com/nlfiedler/zorigami
repository: https://github.com/nlfiedler/zorigami.git
issue_tracker: https://github.com/nlfiedler/zorigami/issues
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  form_builder_validators: ^8.3.0
  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.5.0
  flutter_riverpod: ^2.1.3
  graphql: ^5.1.3
  intl: ^0.17.0
  oxidized: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.3
  environment_config: ^3.1.0
  flutter_lints: ^2.0.1
  http: ^0.13.5
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

environment_config:
  const: true
  fields:
    base_url:
      default: http://127.0.0.1:8080
      env_var: BASE_URL
