name: zorigami
description: Graphical user interface for the zorigami backup/restore application.
version: 1.0.0+1
homepage: https://github.com/nlfiedler/zorigami
repository: https://github.com/nlfiedler/zorigami.git
issue_tracker: https://github.com/nlfiedler/zorigami/issues
publish_to: 'none'

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  #
  # Flutter and dependencies are complicated:
  #
  # 1) Flutter web support requires *beta* channel
  # 2) Beta/dev versions of Flutter have breaking API changes
  # 3) flutter_form_builder is especially sensitive to flutter API changes
  # 4) Even more recent flutter versions break dependencies in other ways
  #
  # c.f. https://github.com/danvick/flutter_form_builder/issues/382
  # c.f. https://github.com/danvick/flutter_form_builder/issues/465
  #
  flutter_form_builder:
    git:
      url: https://github.com/knaeckeKami/flutter_form_builder.git
      ref: v3.14.0-alpha.2-fix
  flutter_riverpod: ^0.12.3+1
  graphql: ^3.1.0
  intl: ^0.16.1
  oxidized: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^7.1.0
  environment_config: ^2.2.5
  http: ^0.12.0+4
  mockito: ^4.1.2
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

environment_config:
  const: true
  fields:
    base_url:
      default: http://127.0.0.1:8080
      env_var: BASE_URL
