name: zorigami
description: Graphical user interface for the zorigami backup/restore application.
version: 1.0.0+1
homepage: https://github.com/nlfiedler/zorigami
repository: https://github.com/nlfiedler/zorigami.git
issue_tracker: https://github.com/nlfiedler/zorigami/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  # specifying dev version of flutter_chips_input to temporarily get around an
  # API incompatibility with beta channel flutter
  flutter_chips_input: ^1.9.0-dev.3
  flutter_form_builder: ^3.8.2
  get_it: ^4.0.0
  graphql: ^3.0.1-beta.3
  intl: ^0.16.1
  oxidized: ^3.1.0
  provider: ^4.0.4
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^4.0.0
  environment_config: ^2.2.0+2
  http: ^0.12.0+4
  mockito: ^4.1.1
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

environment_config:
  const: true
  fields:
    base_url:
      default: http://127.0.0.1:8080
      env_var: BASE_URL
