name: zorigami
description: Graphical interface for the zorigami application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  graphql_flutter: ^3.0.1-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
