name: zorigami
description: Graphical user interface for the zorigami backup/restore application.
version: 1.0.0+1
homepage: https://github.com/nlfiedler/zorigami
repository: https://github.com/nlfiedler/zorigami.git
issue_tracker: https://github.com/nlfiedler/zorigami/issues
publish_to: 'none'

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  flutter_form_builder: ^6.0.0
  flutter_riverpod: ^0.14.0+2
  graphql: ^3.1.0
  intl: ^0.17.0
  oxidized: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^7.1.0
  environment_config: ^2.2.5
  http: ^0.12.0+4
  mockito: ^4.1.2
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

environment_config:
  const: true
  fields:
    base_url:
      default: http://127.0.0.1:8080
      env_var: BASE_URL
