[package]
name = "store_azure"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2021"
license = "UNLICENSED"

[dependencies]
anyhow = "1.0.55"
azure_storage = "0.10.0"
azure_storage_blobs = "0.10.0"
bytes = "1.0"
dotenv = "0.15.0"
futures = "0.3"
store_core = { path = "../store_core" }
tempfile = "3.2"
tokio = { version = "1.24.2", features = ["fs", "rt-multi-thread", "time"] }

[dev-dependencies]
xid = "1.0.0"
