[package]
name = "store_core"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"

[dependencies]
failure = "0.1.6"
md-5 = "0.9.0"

[dev-dependencies]
mockall = "0.9"
