[package]
name = "store_core"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.55"
md-5 = "0.10.1"
thiserror = "1.0.30"

[dev-dependencies]
mockall = "0.13.0"
