[package]
name = "store_minio"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"

[dependencies]
# rusoto requires bytes 0.5 for now
bytes = "0.5"
# bytes = "0.6"
dotenv = "0.15.0"
failure = "0.1.6"
futures = "0.3.5"
rusoto_core = "0.45.0"
rusoto_credential = "0.45.0"
rusoto_s3 = "0.45.0"
store_core = { path = "../store_core" }
tempfile = "3.1.0"
# rusoto requires tokio 0.2 for now
tokio = { version = "0.2", features = ["blocking", "fs", "rt-threaded", "time"] }
# tokio = { version = "0.3", features = ["full"] }
