#
# Define containers used in automated testing.
#
name: zorigami-test
services:
  sftp:
    image: atmoz/sftp
    container_name: zorigami_sftp
    ports:
      - "2222:22"
    command: foo:pass:::upload
    restart: always
  minio:
    #
    # The docker hub readme is seemingly out-of-date, see the docs
    #
    # https://docs.rustfs.com/installation/docker/
    #
    image: rustfs/rustfs:latest
    container_name: zorigami_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: root
      RUSTFS_SECRET_KEY: Passw0rd!
      RUSTFS_CONSOLE_ENABLE: true
    command: "/data"
    restart: always
