[package]
name = "store_google"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
license = "UNLICENSED"

[dependencies]
dotenv = "0.15.0"
failure = "0.1.6"
google-storage1 = "1.0.14"
# This project intentionally uses an old version of hyper. See
# https://github.com/Byron/google-apis-rs/issues/173 for more information.
hyper = "^0.10"
hyper-rustls = "^0.6"
serde = "1.0.119"
serde_json = "1.0.61"
store_core = { path = "../store_core" }
tempfile = "3.1.0"
# This project intentionally uses an old version of yup-oauth2. See
# https://github.com/Byron/google-apis-rs/issues/173 for more information.
yup-oauth2 = "^1.0"
