[package]
name = "store_google"
version = "0.2.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2021"
license = "UNLICENSED"

[dependencies]
anyhow = "1.0.55"
base64 = "0.13"
google-storage1 = "3.0.0"
md-5 = "0.10.1"
serde = "1.0"
store_core = { path = "../store_core" }
tokio = { version = "1.4", features = ["macros", "io-util", "rt", "rt-multi-thread", "fs"] }

[dev-dependencies]
dotenv = "0.15"
tempfile = "3.2"
