[package]
name = "store_google"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2021"
license = "UNLICENSED"

[dependencies]
async-google-apis-common = "0.3"
base64 = "0.13"
failure = "0.1"
hyper = { version = "0.14", features = ["stream"] }
# async-google-apis-common requires hyper-rustls version 0.22
hyper-rustls = { version = "0.22.1", features = ["rustls-native-certs"] }
md-5 = "0.10.1"
serde = "1.0"
store_core = { path = "../store_core" }
tokio = { version = "1.4", features = ["macros", "io-util", "rt", "rt-multi-thread", "fs"] }

[dev-dependencies]
dotenv = "0.15"
tempfile = "3.2"
