[package]
name = "server"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "Backup and restore application."
repository = "https://github.com/nlfiedler/zorigami"
readme = "README.md"
keywords = ["backup", "archival"]
license = "BSD-2-Clause"

[dependencies]
actix = "0.10"
actix-cors = "0.3"
actix-files = "0.3"
actix-rt = "1.1"
actix-web = "3.0"
base64 = "0.12"
blob-uuid = "0.4.0"
chrono = { version = "0.4", features = ["serde"] }
database_core = { path = "../database/database_core" }
database_rocks = { path = "../database/database_rocks" }
dotenv = "0.15.0"
env_logger = "0.7.0"
failure = "0.1.6"
failure_derive = "0.1.6"
fastcdc = "1.0.1"
flate2 = "1.0"
juniper = "0.14.0"
lazy_static = "1.3.0"
libc = "0.2.60"
log = "0.4.7"
memmap = "0.7.0"
reducer = "2.0"
rusty_ulid = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
serde_json = "1.0"
sha-1 = "0.9.0"
sha2 = "0.9.0"
sodiumoxide = "0.2.4"
store_core = { path = "../stores/store_core" }
store_google = { path = "../stores/store_google" }
store_local = { path = "../stores/store_local" }
store_minio = { path = "../stores/store_minio" }
store_sftp = { path = "../stores/store_sftp" }
tar = "0.4.26"
tempfile = "3.1.0"
uuid = { version = "0.8", features = ["serde", "v4", "v5"] }
whoami = "0.9"

[target.'cfg(unix)'.dependencies]
xattr = "0.2.2"

[dev-dependencies]
mockall = "0.8"
rocksdb = "0.15"
