[package]
name = "server"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2021"
description = "Backup and restore application."
repository = "https://github.com/nlfiedler/zorigami"
readme = "README.md"
keywords = ["backup", "archival"]
license = "UNLICENSED"

[dependencies]
actix = "0.13.0"
actix-cors = "0.6.0"
actix-files = "0.6.0"
actix-rt = "2.8.0"
actix-web = "4.3.0"
anyhow = "1.0.55"
base64 = "0.21.0"
blob-uuid = "0.5.0"
chrono = { version = "0.4", features = ["serde"] }
database_core = { path = "../database/database_core" }
database_rocks = { path = "../database/database_rocks" }
dotenv = "0.15.0"
env_logger = "0.10.0"
fastcdc = "3.0.0"
flate2 = "1.0.25"
globset = "0.4.8"
juniper = "0.15.9"
lazy_static = "1.3.0"
libc = "0.2.119"
log = "0.4.7"
memmap2 = "0.5.8"
reducer = "3.0"
rusty_ulid = "1.0.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_cbor = "0.11"
serde_json = "1.0.79"
sha-1 = "0.10.0"
sha2 = "0.10.2"
sodiumoxide = "0.2.7"
store_amazon = { path = "../stores/store_amazon" }
store_azure = { path = "../stores/store_azure" }
store_core = { path = "../stores/store_core" }
store_google = { path = "../stores/store_google" }
store_local = { path = "../stores/store_local" }
store_minio = { path = "../stores/store_minio" }
store_sftp = { path = "../stores/store_sftp" }
tar = "0.4.38"
tempfile = "3.2.0"
thiserror = "1.0.30"
uuid = { version = "1.1.2", features = ["serde", "v4", "v5"] }
whoami = "1.0"
xid = "1.0.0"

[target.'cfg(unix)'.dependencies]
xattr = "1.0.0"

[dev-dependencies]
mockall = "0.11.0"
rocksdb = "0.19.0"
serial_test = "1.0.0"
