[package]
name = "server"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2021"
description = "Backup and restore application."
repository = "https://github.com/nlfiedler/zorigami"
readme = "README.md"
keywords = ["backup", "archival"]
license = "UNLICENSED"

[[bin]]
name = "zorigami"
path = "src/main.rs"

[dependencies]
actix = "0.13.0"
actix-cors = "0.7.0"
actix-files = "0.6.0"
actix-rt = "2.8.0"
actix-web = "4.3.0"
anyhow = "1.0.55"
base64 = "0.22.1"
blob-uuid = "0.5.0"
bloomfilter = "1.0.9"
chrono = { version = "0.4", features = ["serde"] }
database_core = { path = "../database/database_core" }
database_rocks = { path = "../database/database_rocks" }
dotenv = "0.15.0"
env_logger = "0.11.0"
exaf-rs = "1.1.1"
fastcdc = "3.0.0"
globset = "0.4.13"
juniper = "0.15.9"
lazy_static = "1.3.0"
libc = "0.2.119"
log = "0.4.7"
memmap2 = "0.9.4"
os_str_bytes = { version = "6.6.1", features = ["conversions"] }
reducer = "3.0"
serde = { version = "1.0.182", features = ["derive"] }
serde_cbor = "0.11"
serde_json = "1.0.79"
sha1 = "0.10.6"
sha2 = "0.10.2"
store_amazon = { path = "../stores/store_amazon" }
store_azure = { path = "../stores/store_azure" }
store_core = { path = "../stores/store_core" }
store_google = { path = "../stores/store_google" }
store_local = { path = "../stores/store_local" }
store_minio = { path = "../stores/store_minio" }
store_sftp = { path = "../stores/store_sftp" }
tempfile = "3.7.1"
thiserror = "1.0.30"
ulid = "1.1.2"
uuid = { version = "1.1.2", features = ["serde", "v4", "v5"] }
whoami = "1.5.1"
xid = "1.0.0"

[target.'cfg(unix)'.dependencies]
xattr = "1.0.0"

[dev-dependencies]
mockall = "0.12.1"
rocksdb = "0.22.0"
serial_test = "3.0.0"
