[package]
name = "store_local"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2021"
license = "UNLICENSED"

[dependencies]
anyhow = "1.0.55"
store_core = { path = "../store_core" }
tempfile = "3.7.1"
