[package]
name = "database_rocks"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2021"
license = "MIT"

[dependencies]
database_core = { path = "../database_core" }
anyhow = "1.0.55"
rocksdb = "0.23.0"
